### ISSUE TITLE
Execution with Values

### ISSUE THREAD

**Issue by Yipyipyip** [headacheboy/IGSQL#1]
First of all, thanks a lot for sharing your code! I was able to train the model and reproduce some impressive results.
I'm almost sure that I saw IGSQL on the "Execution with Values" SParC leaderboard too, however it seems gone now. In accordance to that, IGSQL also never outputs any values in WHERE clauses (more precisely, the model outputs "value" which is replaced with 1 in postprocessing, just like EditSQL). Now that I thought I saw IGSQL on that leaderboard, I'm curious: Did you ever tackle this feature? If so, could you give me a few pointers?

**Comment by headacheboy** [comment]
Hi, 

Thank you for your attention.

In this paper, we do not attempt to predict the exact value of SQL queries. 
Maybe the administrator had made some mistakes when updating the SParC leaderboard and then corrected them.

**Comment by Yipyipyip** [comment]
Thank you for the quick response! That probably saved me some hours of time trying to make it work with values :)
